Repository q-asker/api, pull requests merged in 2025-06, with the labels that each got.

#16 [ICC-52] 연결 수정 사항 추가
  src/main/java/com/icc/qasker/quiz/dto/request/FeGenerationRequest.java
  src/main/java/com/icc/qasker/quiz/dto/response/ProblemSetResponse.java
Labels: 리팩토링

#20 [ICC-71] generation dto 형식 수정
  src/main/java/com/icc/qasker/global/error/ExceptionMessage.java
  src/main/java/com/icc/qasker/quiz/controller/GenerationController.java
  src/main/java/com/icc/qasker/quiz/dto/request/FeGenerationRequest.java
Labels: 구현, 리팩토링

#22 [ICC-78] ai 서버 에러 메시지 출력추가
  src/main/java/com/icc/qasker/quiz/dto/request/FeGenerationRequest.java
  src/main/java/com/icc/qasker/quiz/service/GenerationService.java
Labels: 구현
