Repository q-asker/api, pull requests merged in 2025-05, with the labels that each got.

#3 [ICC-22] mysql 도커 컴포즈 작성
  .gitignore
  docker-compose.yml
Labels: 문서

#6 [ICC-24] 작성 완료
  .github/PULL_REQUEST_TEMPLATE.md
  .gitignore
  build.gradle
  src/main/java/com/icc/qasker/global/config/WebConfig.java
  src/test/java/com/icc/qasker/QAskerApplicationTests.java
Labels: 문서

#7 [ICC-27] cicd
  .github/workflows/dev_deploy.yml
Labels: 문서, 구현

#8 [ICC-17] FE 문제 채점 기능
  .gitignore
  build.gradle
  docker-compose.yml
  src/main/java/com/icc/qasker/global/error/ExceptionMessage.java
  src/main/java/com/icc/qasker/quiz/controller/ExplanationController.java
  src/main/java/com/icc/qasker/quiz/dto/request/AnswerRequest.java
  src/main/java/com/icc/qasker/quiz/dto/request/ExplanationRequest.java
  src/main/java/com/icc/qasker/quiz/dto/response/ExplanationResponse.java
  src/main/java/com/icc/qasker/quiz/dto/response/ResultResponse.java
  src/main/java/com/icc/qasker/quiz/entity/Explanation.java
  src/main/java/com/icc/qasker/quiz/entity/Problem.java
  src/main/java/com/icc/qasker/quiz/entity/ProblemId.java
  src/main/java/com/icc/qasker/quiz/entity/ProblemSet.java
  src/main/java/com/icc/qasker/quiz/entity/Selection.java
  src/main/java/com/icc/qasker/quiz/repository/ProblemRepository.java
  src/main/java/com/icc/qasker/quiz/service/ExplanationService.java
  src/test/java/com/icc/qasker/service/ExplanationServiceTest.java
Labels: 구현
